from dataclasses import dataclass

@dataclass
class model_config:
    num_classes: int = 100
    conv1_out_channels: int = ...
    conv2_out_channels: int = ...
    conv3_out_channels: int = ...
    ...

@dataclass
class training_config:
    batch_size: int = ...
    num_workers: int = ...
    learning_rate: float = ...
    num_epochs: int = ...
    weight_decay: float = ...
    ...